name: kyla_budget_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mrx_charts: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/mock_transactions.json
    - assets/james.jpeg

  uses-material-design: true
